name: ES
author: Taki21
api: 1.0.0
version: 0.0.1
main: Taki21\ES\Main
commands:
 playsounds:
  usage: /playsounds
  description: Plays sounds.
 s1:
  usage: /s1
  description: Plays AnvilFallSound.
 s2:
  usage: /s2
  description: Plays BlazeShootSound.
 s3:
  usage: /s3
  description: Plays ButtonClickSound.
 s4:
  usage: /s4
  description: Plays DoorSound.
 s5:
  usage: /s5
  description: Plays EndermanTeleportSound.
 s6:
  usage: /s6
  description: Plays FizzSound.
 s7:
  usage: /s7
  description: Plays GhastShootSound.
 s8:
  usage: /s8
  description: Plays LaunchSound.
 s9:
  usage: /s9
  description: Plays NoteblockSound.
 s10: 
  usage: /s10
  description: Plays PopSound.
 s11:
  usage: /s11
  description: Plays ZombieHealSound.
